language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "arc-menu:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: C6YgxCMoXHW7GaNNFVlnsLZ5EKmYMRCLEbCjyUi6xn9KHrKMPDpbK0GaNr3VgN1AXAWfWiyCz41QBzdOI3wzdTtu9tA7HK1LjKKgXLPjjQV44ncaLXlHsMuw36Lhu9aswd65kWa6lpQaFPToLZawBpqSr7UcW7a6RctZLybiqlNH8k2veY80e57Pr6hX4ueqNC9ZdBgBLvV5NKaB2knbkCuszY1cxUnMsOgSFvhzwxdXr1OyvfmHRiqABlyxDEEQJJA9+fNe66xVM0pRGLQgMQQvZeY4FAt06n7qrazX/ezknnXEabQIdB2DWVZTEB7udwJ+tWn/Kg66Ro1aYAvE9VXL45EuDoUWgoIn1jTmAW0tr03TvQR1tl8g1dQ3FUwA1/fQJYdFUxiaKUwE+bybw6NCMlrZDjq/HGjcqA2egzOCVkbHmWDjisNg/iylSn6r5wrcW1YgNPw2M0btisiUBDLmJkhurE+4uUOfI4/kWpuQHrxWlNV9u+l8UnMGI+lnAhSsymS8iOkdd7TN/z5xowQoQ3QxlHCg6v7hePPRTxq6NvjDoYKIAW4A1eTvYk0b7lVFX7CrzHRP6wxM3bUakvx68+nc6+kgo+zX0fo9lcTesMqerBgpoWZRZnYzOah7RiMO1nzzmZZSXjdE6wGfs/PpWlVrkK+1eCS4oI8w5oU=
  - secure: E04JrerneT7SgBqH9A4tlZDsra7jznaP17SAyqnz/OcYpP+qnp5eEjmPyIK1PmGdioQE/DQYojST0F5F9gwNxRrxuJjbyW7Bwwcr3s3wEhh7u7NDrA6H7WnNXlh5hr15PkwGkOLjOaE8zf+g2QZgC+jnf8wkx/XsG1ROJF4BrK1e+0wO5o9c28rtT1Rwy39+ZhDQu3v7wqarIVBeBhcFu+I4e/Xpx7w+kA1YhqHUomWFxPf3LHATr58DsUj/l45V9AxUAYG4Iw2lKdwvNucp8+7onSuRNF8nfkxdX72RhE6vFDyS9gexLu1b0YjPb4viogK/V7VKnZwFbXCOmduNMf8GBtav5wdeixAnALydWOi2QWRUpr+Q41eQYkBY2rbbOeWmW+gw+Xqg7JzBnXkPhJpq3TiUhQKxigw8pE+55xfd+P71aBy7ZzFS3c7EHeRCeCkOJKvALpRvPZA0+LoMC2n/GJqtEtidKmvsE7Fvu2Ymx7ffqqAotZcS/RKrGq1sQ6Ohi77hqDXhW2+lyLlwGxYYa2JzuTnyKW5UIF790FmQ/IxHg8tRAAXfDNRRi5oFO/QMaAxOIV+AvEXy6CPyNrw3JnOItDuzPKCMii7ITr04JJ2mBvCAHvEtIYqmGr3H+/XHDBC0go81YBkCnPecHZ8bF8oYcwlGEuFzQBAqj+o=
